<a href="https://colab.research.google.com/github/shani1610/pytorch-for-deep-learning/blob/main/course_exercises/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch


In [5]:
# Create random tensor
random_tensor_A = torch.rand([7,7])

In [6]:
random_tensor_A

tensor([[0.2934, 0.7311, 0.8393, 0.6694, 0.6615, 0.7052, 0.4920],
        [0.1653, 0.4898, 0.3388, 0.9044, 0.6679, 0.4868, 0.7794],
        [0.8637, 0.2025, 0.9490, 0.0882, 0.1746, 0.4295, 0.1787],
        [0.4810, 0.5978, 0.2016, 0.9564, 0.3026, 0.6130, 0.0041],
        [0.1338, 0.2466, 0.5809, 0.6792, 0.7877, 0.9396, 0.8678],
        [0.9778, 0.9538, 0.8432, 0.7072, 0.8052, 0.8821, 0.8133],
        [0.2565, 0.6147, 0.9467, 0.6744, 0.4240, 0.2851, 0.3802]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [7]:
# Create another random tensor
random_tensor_B = torch.rand([1,7])

In [9]:
# Perform matrix multiplication
tensor_C = torch.matmul(random_tensor_A, random_tensor_B.T)

In [12]:
random_tensor_A.shape, random_tensor_B.shape, tensor_C.shape

(torch.Size([7, 7]), torch.Size([1, 7]), torch.Size([7, 1]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [13]:
import random

# Set manual seed
RANDOM_SEED=0
torch.manual_seed(seed=RANDOM_SEED)

# Create two random tensors
random_tensor_A = torch.rand([7,7])
random_tensor_B = torch.rand([1,7])

# Matrix multiply tensors
tensor_C = torch.matmul(random_tensor_A, random_tensor_B.T)

In [14]:
tensor_C

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [16]:
torch.cuda.is_available()

True

In [15]:
# Set random seed on the GPU
RANDOM_SEED=1234
torch.cuda.manual_seed(seed=RANDOM_SEED)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [17]:
# Set random seed
import random

# Set manual seed
RANDOM_SEED=1234
torch.manual_seed(seed=RANDOM_SEED)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device:{device}")

# Create two random tensors on GPU
random_tensor_A = torch.rand([2,3])
random_tensor_B = torch.rand([2,3])

random_tensor_A_on_gpu = random_tensor_A.to(device)
random_tensor_B_on_gpu = random_tensor_B.to(device)

random_tensor_A_on_gpu, random_tensor_B_on_gpu

Device:cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [18]:
# Perform matmul on tensor_A and tensor_B
tensor_C = torch.matmul(random_tensor_A_on_gpu, random_tensor_B_on_gpu.T)
tensor_C, tensor_C.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [21]:
# Find max
tensor_C.max()



tensor(0.5617, device='cuda:0')

In [22]:
# Find min
tensor_C.min()

tensor(0.3647, device='cuda:0')

### 9. Find the maximum and minimum index values of the output of 7.

In [23]:
# Find arg max
tensor_C.argmax()

tensor(3, device='cuda:0')

In [25]:
# Find arg min
tensor_C.argmin()

tensor(0, device='cuda:0')


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [28]:
# Set seed
import random
RANDOM_SEED=7
torch.manual_seed(seed=RANDOM_SEED)

# Create random tensor
random_tensor = torch.rand([1, 1, 1, 10])
print(f"tensor before:{random_tensor}, its shape:{random_tensor.shape}")

# Remove single dimensions
random_tensor_new = random_tensor.squeeze()
print(f"tensor after:{random_tensor_new}, its shape:{random_tensor_new.shape}")

# Print out tensors and their shapes

tensor before:tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]), its shape:torch.Size([1, 1, 1, 10])
tensor after:tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]), its shape:torch.Size([10])
